# -*- coding: utf-8 -*-
"""new.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lMsELjhwMVyDb8vc-o0QV6doGc8m3fte
"""

import pandas as pd

def read_wb_data(filename):
    # Read Excel file into a dataframe
    df = pd.read_excel(filename)

    # Transpose the dataframe and set the first column as the index
    df_transposed = df.transpose()
    df_transposed.columns = df_transposed.iloc[0]
    df_transposed = df_transposed.iloc[1:]

    # Split the transposed dataframe into two dataframes
    df_years = df_transposed.iloc[:, :-1]
    df_countries = df_transposed.iloc[:, -1:]

    # Clean the dataframes
    df_countries = df_countries.rename(columns={df_countries.columns[0]: "Country"})

    return df_years, df_countries

filename = "/content/data.xlsx"
df_years, df_countries = read_wb_data(filename)

# Use the dataframes as needed
print(df_years)
print(df_countries)

df = pd.read_excel("/content/data.xlsx")
df.describe()

import matplotlib.pyplot as plt
df.plot()

# Show the plot
plt.show()

x = df['1975']
y = df['2005']

plt.plot(x, y)

# add title and axis labels
plt.title("Line Graph")
plt.xlabel("1975")
plt.ylabel("2005")

df.head()

# Summary statistics for GDP per capita
df['Indicator Code'].describe()

# Compute the correlation matrix between the indicators
corr = df[['Country Code', 'Indicator Code', '2015']].corr()

# Display the correlation matrix
corr

# Generate a heatmap of the correlation matrix
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.show()

df_cor = df.corr()

sns.heatmap(df_cor, annot=True, cmap='coolwarm')
plt.show()

grouped_df = df.groupby('Indicator Name').corr()

# Generate a heatmap of the correlation matrix for a specific country
sns.heatmap(grouped_df.loc['Agricultural land (% of land area)'], annot=True, cmap='coolwarm')
plt.title('Correlation matrix for Agricultural land')
plt.show()

import pandas as pd
df = pd.read_excel("/content/API_19_DS2_en_excel_v2_5252304 (1) (1).xls", sheet_name='Data')
import seaborn as sns
import matplotlib.pyplot as plt
indicators = ['SP.POP.TOTL', 'NY.GDP.PCAP.CD', 'NY.GDP.MKTP.KD.ZG']
df_filtered = df[df['Unnamed: 3'].isin(indicators)]
# Compute correlation between indicators
df_corr = df_filtered.corr()

# Plot a heatmap of the correlation matrix
sns.heatmap(df_corr, cmap="YlGnBu")
plt.title("World Bank Indicators")
plt.show()

